/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.api.teste;

import org.apache.http.HttpStatus;
import org.junit.Test;
import qaops.api.dominio.Usuario;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class TestUsuario extends TestBase {

    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIAR_USUARIOS_ENDPOINT = "/user";

    @Test
    public void testeMostraPaginaEspecifica() {
        given()
                .params("page", "2").
        when(). //Quando
                get(LISTA_USUARIOS_ENDPOINT). //endpoint
                then(). //o que espero
                        statusCode(HttpStatus.SC_OK) //Verbo HTTP 200
                          .body("page", is(2))
                            .body("data", is(notNullValue()));
    }

    @Test
    public void testeCriaUsuarioComSucesso(){
        Usuario usuario = new Usuario("renato", "qa-analyst", "email@gmail.com");
        given()
                .body(usuario).
                when() //Depois do when devemos inserir qual verbo será destacado
                    .post(CRIAR_USUARIOS_ENDPOINT).
                then() //Then é o resultado a ser exibido, validação
                    .statusCode(HttpStatus.SC_CREATED).
                    body("name",is("renato"));

    }
}
