/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.api.teste;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;
import qaops.api.dominio.Usuario;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class UsuarioTeste {

    @BeforeClass
    public static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        baseURI = "https://reqres.in";
        basePath = "/api";
    }

    @Test
    public void testListMetadadoosUsuario() {
        given()
                .params("page", "2").
        when(). //Quando
                get("/users"). //endpoint
                then(). //o que espero
                        statusCode(HttpStatus.SC_OK) //Verbo HTTP 200
                          .body("page", is(2))
                            .body("data", is(notNullValue()));
    }

    @Test
    public void testeCriarUserComSucesso(){
        Usuario usuario = new Usuario("renato", "qa-analyst", "email@gmail.com");
        given()
                .contentType(ContentType.JSON)
                .body(usuario).
                when() //Depois do when devemos inserir qual verbo será destacado
                    .post("/user").
                then() //Then é o resultado a ser exibido, validação
                    .statusCode(HttpStatus.SC_CREATED).
                    body("name",is("renato"));

    }
}
