/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.api;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class AppTest {

    @BeforeClass
    public static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    public void testListMetadadoosUsuario() {
        when(). //Quando
                get("https://reqres.in/api/users?page=2"). //endpoint
                then(). //o que espero
                        statusCode(HttpStatus.SC_OK) //Verbo HTTP 200
                          .body("page", is(2))
                            .body("data", is(notNullValue()));
    }

    @Test
    public void testeCriarUserComSucesso(){
        given().log().all()
                .contentType(ContentType.JSON)
                .body("{\n" +
                        "    \"name\": \"renato\",\n" +
                        "    \"job\": \"qa-analyst\"\n" +
                        "}").
                when()
                    .post("https://reqres.in/api/users").
                then()
                    .statusCode(HttpStatus.SC_CREATED).
                    body("name",is("renato"));

    }
}
